/**
 * Game commodity definitions: crops, animal produce, fishing, and crafted items.
 * This is the single source of truth for all farmable/craftable item metadata.
 */

export type CommodityCategory = "crop" | "animal" | "fishing" | "crafted";

export interface RecipeIngredient {
  id: string;
  qty: number;
}

export interface GameCropDef {
  id: string;
  name: string;
  tier: 1 | 2 | 3 | "special";
  base_price: number;
  peg: string;
  category: CommodityCategory;
  recipe?: RecipeIngredient[];
}

// ── Peg key constants (match keys used in engine.ts PEG_* vars) ──────────────
const PEG_WHEAT = "wheat";
const PEG_CORN = "corn";
const PEG_SOYBEANS = "soybeans";
const PEG_SUGARCANE = "sugarcane";
const PEG_COTTON = "cotton";
const PEG_COFFEE = "coffee";

export const GAME_CROPS: GameCropDef[] = [
  // ── Crops: Tier 1 ─────────────────────────────────────────────────────────
  {
    id: "wheat",
    name: "Wheat",
    tier: 1,
    base_price: 15,
    peg: PEG_WHEAT,
    category: "crop",
  },
  {
    id: "carrot",
    name: "Carrot",
    tier: 1,
    base_price: 22,
    peg: PEG_WHEAT,
    category: "crop",
  },
  {
    id: "corn",
    name: "Corn",
    tier: 1,
    base_price: 18,
    peg: PEG_CORN,
    category: "crop",
  },
  {
    id: "lettuce",
    name: "Lettuce",
    tier: 1,
    base_price: 20,
    peg: PEG_WHEAT,
    category: "crop",
  },
  // ── Crops: Tier 2 ─────────────────────────────────────────────────────────
  {
    id: "tomato",
    name: "Tomato",
    tier: 2,
    base_price: 55,
    peg: PEG_CORN,
    category: "crop",
  },
  {
    id: "sugarcane",
    name: "Sugarcane",
    tier: 2,
    base_price: 70,
    peg: PEG_SUGARCANE,
    category: "crop",
  },
  {
    id: "potato",
    name: "Potato",
    tier: 2,
    base_price: 75,
    peg: PEG_CORN,
    category: "crop",
  },
  {
    id: "cotton",
    name: "Cotton",
    tier: 2,
    base_price: 90,
    peg: PEG_COTTON,
    category: "crop",
  },
  {
    id: "sunflower",
    name: "Sunflower",
    tier: 2,
    base_price: 95,
    peg: PEG_SOYBEANS,
    category: "crop",
  },
  // ── Crops: Tier 3 ─────────────────────────────────────────────────────────
  {
    id: "pumpkin",
    name: "Pumpkin",
    tier: 3,
    base_price: 180,
    peg: PEG_CORN,
    category: "crop",
  },
  {
    id: "watermelon",
    name: "Watermelon",
    tier: 3,
    base_price: 350,
    peg: PEG_SUGARCANE,
    category: "crop",
  },
  {
    id: "strawberries",
    name: "Strawberries",
    tier: 3,
    base_price: 200,
    peg: PEG_SUGARCANE,
    category: "crop",
  },
  {
    id: "blueberries",
    name: "Blueberries",
    tier: 3,
    base_price: 220,
    peg: PEG_SUGARCANE,
    category: "crop",
  },
  {
    id: "coffee",
    name: "Coffee Beans",
    tier: 3,
    base_price: 280,
    peg: PEG_COFFEE,
    category: "crop",
  },
  // ── Crops: Special / Utility dyes ─────────────────────────────────────────
  {
    id: "indigo",
    name: "Indigo Flower",
    tier: "special",
    base_price: 150,
    peg: PEG_COTTON,
    category: "crop",
  },
  {
    id: "marigold",
    name: "Marigold",
    tier: "special",
    base_price: 130,
    peg: PEG_COTTON,
    category: "crop",
  },
  {
    id: "madder",
    name: "Madder Root",
    tier: "special",
    base_price: 160,
    peg: PEG_COTTON,
    category: "crop",
  },
  // ── Animal produce ────────────────────────────────────────────────────────
  {
    id: "egg",
    name: "Egg",
    tier: 1,
    base_price: 28,
    peg: PEG_CORN,
    category: "animal",
  },
  {
    id: "golden_egg",
    name: "Golden Egg",
    tier: "special",
    base_price: 500,
    peg: PEG_CORN,
    category: "animal",
  },
  {
    id: "milk",
    name: "Milk",
    tier: 2,
    base_price: 65,
    peg: PEG_CORN,
    category: "animal",
  },
  {
    id: "rich_milk",
    name: "Rich Milk",
    tier: "special",
    base_price: 150,
    peg: PEG_CORN,
    category: "animal",
  },
  {
    id: "honeycomb",
    name: "Honeycomb",
    tier: 2,
    base_price: 55,
    peg: PEG_SUGARCANE,
    category: "animal",
  },
  {
    id: "raw_honey",
    name: "Raw Honey",
    tier: 2,
    base_price: 75,
    peg: PEG_SUGARCANE,
    category: "animal",
  },
  {
    id: "royal_jelly",
    name: "Royal Jelly",
    tier: "special",
    base_price: 400,
    peg: PEG_SUGARCANE,
    category: "animal",
  },
  {
    id: "pork",
    name: "Pork",
    tier: 2,
    base_price: 95,
    peg: PEG_CORN,
    category: "animal",
  },
  {
    id: "truffle",
    name: "Truffle",
    tier: "special",
    base_price: 600,
    peg: PEG_CORN,
    category: "animal",
  },
  {
    id: "raw_wool",
    name: "Raw Wool",
    tier: 2,
    base_price: 55,
    peg: PEG_COTTON,
    category: "animal",
  },
  // ── Fishing: Shallows ─────────────────────────────────────────────────────
  {
    id: "sardine",
    name: "Sardine",
    tier: 1,
    base_price: 22,
    peg: PEG_CORN,
    category: "fishing",
  },
  {
    id: "seaweed",
    name: "Seaweed",
    tier: 1,
    base_price: 18,
    peg: PEG_CORN,
    category: "fishing",
  },
  {
    id: "old_boot",
    name: "Old Boot",
    tier: 1,
    base_price: 5,
    peg: PEG_CORN,
    category: "fishing",
  },
  // ── Fishing: Reef ─────────────────────────────────────────────────────────
  {
    id: "salmon",
    name: "Salmon",
    tier: 2,
    base_price: 70,
    peg: PEG_CORN,
    category: "fishing",
  },
  {
    id: "squid",
    name: "Squid",
    tier: 2,
    base_price: 60,
    peg: PEG_CORN,
    category: "fishing",
  },
  // ── Fishing: Deep Sea ─────────────────────────────────────────────────────
  {
    id: "lobster",
    name: "Lobster",
    tier: 3,
    base_price: 290,
    peg: PEG_CORN,
    category: "fishing",
  },
  {
    id: "oyster",
    name: "Oyster",
    tier: 3,
    base_price: 180,
    peg: PEG_CORN,
    category: "fishing",
  },
  {
    id: "pearl",
    name: "Pearl",
    tier: "special",
    base_price: 800,
    peg: PEG_CORN,
    category: "fishing",
  },
  // ── Crafted Layer 1: Processing intermediaries (raw → refined) ────────────
  {
    id: "flour",
    name: "Flour",
    tier: 1,
    base_price: 42,
    peg: PEG_WHEAT,
    category: "crafted",
    recipe: [{ id: "wheat", qty: 2 }],
  },
  {
    id: "cornmeal",
    name: "Cornmeal",
    tier: 1,
    base_price: 48,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [{ id: "corn", qty: 2 }],
  },
  {
    id: "sugar",
    name: "White Sugar",
    tier: 2,
    base_price: 145,
    peg: PEG_SUGARCANE,
    category: "crafted",
    recipe: [{ id: "sugarcane", qty: 2 }],
  },
  {
    id: "cooking_oil",
    name: "Cooking Oil",
    tier: 2,
    base_price: 185,
    peg: PEG_SOYBEANS,
    category: "crafted",
    recipe: [{ id: "sunflower", qty: 2 }],
  },
  {
    id: "tomato_paste",
    name: "Tomato Paste",
    tier: 2,
    base_price: 120,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [{ id: "tomato", qty: 2 }],
  },
  {
    id: "thread",
    name: "Thread",
    tier: 1,
    base_price: 135,
    peg: PEG_COTTON,
    category: "crafted",
    recipe: [{ id: "cotton", qty: 1 }],
  },
  {
    id: "butter",
    name: "Butter",
    tier: 2,
    base_price: 160,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [{ id: "milk", qty: 2 }],
  },
  {
    id: "beeswax",
    name: "Beeswax",
    tier: 2,
    base_price: 130,
    peg: PEG_SUGARCANE,
    category: "crafted",
    recipe: [{ id: "honeycomb", qty: 2 }],
  },
  {
    id: "yarn",
    name: "Yarn",
    tier: 2,
    base_price: 195,
    peg: PEG_COTTON,
    category: "crafted",
    recipe: [{ id: "raw_wool", qty: 2 }],
  },
  {
    id: "squid_ink",
    name: "Squid Ink",
    tier: 2,
    base_price: 140,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [{ id: "squid", qty: 2 }],
  },
  // ── Crafted Layer 2: Simple goods (raw + layer-1 inputs) ──────────────────
  {
    id: "bread",
    name: "Bread",
    tier: 1,
    base_price: 85,
    peg: PEG_WHEAT,
    category: "crafted",
    recipe: [
      { id: "flour", qty: 1 },
      { id: "egg", qty: 1 },
    ],
  },
  {
    id: "salad",
    name: "Salad",
    tier: 1,
    base_price: 95,
    peg: PEG_WHEAT,
    category: "crafted",
    recipe: [
      { id: "lettuce", qty: 2 },
      { id: "tomato", qty: 1 },
    ],
  },
  {
    id: "grilled_fish",
    name: "Grilled Fish",
    tier: 1,
    base_price: 70,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [{ id: "sardine", qty: 2 }],
  },
  {
    id: "ketchup",
    name: "Ketchup",
    tier: 2,
    base_price: 155,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [
      { id: "tomato_paste", qty: 1 },
      { id: "sugar", qty: 1 },
    ],
  },
  {
    id: "mayonnaise",
    name: "Mayonnaise",
    tier: 2,
    base_price: 175,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [
      { id: "egg", qty: 2 },
      { id: "cooking_oil", qty: 1 },
    ],
  },
  {
    id: "cheese",
    name: "Cheese",
    tier: 2,
    base_price: 200,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [
      { id: "milk", qty: 2 },
      { id: "flour", qty: 1 },
    ],
  },
  {
    id: "jar_of_honey",
    name: "Jar of Honey",
    tier: 2,
    base_price: 165,
    peg: PEG_SUGARCANE,
    category: "crafted",
    recipe: [{ id: "raw_honey", qty: 2 }],
  },
  {
    id: "candle",
    name: "Candle",
    tier: 2,
    base_price: 185,
    peg: PEG_SUGARCANE,
    category: "crafted",
    recipe: [
      { id: "beeswax", qty: 1 },
      { id: "thread", qty: 1 },
    ],
  },
  {
    id: "bacon",
    name: "Bacon",
    tier: 2,
    base_price: 215,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [
      { id: "pork", qty: 1 },
      { id: "cooking_oil", qty: 1 },
    ],
  },
  {
    id: "fabric",
    name: "Fabric",
    tier: 2,
    base_price: 310,
    peg: PEG_COTTON,
    category: "crafted",
    recipe: [{ id: "thread", qty: 2 }],
  },
  {
    id: "blue_dye",
    name: "Blue Dye",
    tier: 2,
    base_price: 240,
    peg: PEG_COTTON,
    category: "crafted",
    recipe: [{ id: "indigo", qty: 2 }],
  },
  {
    id: "yellow_dye",
    name: "Yellow Dye",
    tier: 2,
    base_price: 210,
    peg: PEG_COTTON,
    category: "crafted",
    recipe: [{ id: "marigold", qty: 2 }],
  },
  {
    id: "red_dye",
    name: "Red Dye",
    tier: 2,
    base_price: 260,
    peg: PEG_COTTON,
    category: "crafted",
    recipe: [{ id: "madder", qty: 2 }],
  },
  {
    id: "crop_fertilizer",
    name: "Crop Fertilizer",
    tier: 2,
    base_price: 90,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [{ id: "seaweed", qty: 3 }],
  },
  {
    id: "roasted_coffee",
    name: "Roasted Coffee",
    tier: 3,
    base_price: 360,
    peg: PEG_COFFEE,
    category: "crafted",
    recipe: [{ id: "coffee", qty: 2 }],
  },
  {
    id: "watermelon_juice",
    name: "Watermelon Juice",
    tier: 3,
    base_price: 430,
    peg: PEG_SUGARCANE,
    category: "crafted",
    recipe: [
      { id: "watermelon", qty: 1 },
      { id: "sugar", qty: 1 },
    ],
  },
  {
    id: "strawberry_jam",
    name: "Strawberry Jam",
    tier: 3,
    base_price: 340,
    peg: PEG_SUGARCANE,
    category: "crafted",
    recipe: [
      { id: "strawberries", qty: 2 },
      { id: "sugar", qty: 1 },
    ],
  },
  {
    id: "blueberry_jam",
    name: "Blueberry Jam",
    tier: 3,
    base_price: 360,
    peg: PEG_SUGARCANE,
    category: "crafted",
    recipe: [
      { id: "blueberries", qty: 2 },
      { id: "sugar", qty: 1 },
    ],
  },
  // ── Crafted Layer 3: Premium multi-ingredient goods ────────────────────────
  {
    id: "cake",
    name: "Cake",
    tier: 3,
    base_price: 480,
    peg: PEG_WHEAT,
    category: "crafted",
    recipe: [
      { id: "flour", qty: 2 },
      { id: "egg", qty: 2 },
      { id: "sugar", qty: 1 },
      { id: "butter", qty: 1 },
    ],
  },
  {
    id: "pasta",
    name: "Pasta",
    tier: 2,
    base_price: 210,
    peg: PEG_WHEAT,
    category: "crafted",
    recipe: [
      { id: "flour", qty: 2 },
      { id: "egg", qty: 2 },
    ],
  },
  {
    id: "pizza",
    name: "Pizza",
    tier: 3,
    base_price: 450,
    peg: PEG_WHEAT,
    category: "crafted",
    recipe: [
      { id: "flour", qty: 1 },
      { id: "tomato_paste", qty: 1 },
      { id: "cheese", qty: 1 },
    ],
  },
  {
    id: "hearty_stew",
    name: "Hearty Stew",
    tier: 3,
    base_price: 340,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [
      { id: "pork", qty: 1 },
      { id: "carrot", qty: 1 },
      { id: "potato", qty: 1 },
    ],
  },
  {
    id: "fish_and_chips",
    name: "Fish & Chips",
    tier: 2,
    base_price: 260,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [
      { id: "salmon", qty: 1 },
      { id: "potato", qty: 2 },
    ],
  },
  {
    id: "strawberry_ice_cream",
    name: "Strawberry Ice Cream",
    tier: 3,
    base_price: 420,
    peg: PEG_SUGARCANE,
    category: "crafted",
    recipe: [
      { id: "milk", qty: 1 },
      { id: "sugar", qty: 1 },
      { id: "strawberries", qty: 2 },
    ],
  },
  {
    id: "pumpkin_pie",
    name: "Pumpkin Pie",
    tier: 3,
    base_price: 490,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [
      { id: "pumpkin", qty: 1 },
      { id: "flour", qty: 1 },
      { id: "sugar", qty: 1 },
      { id: "egg", qty: 1 },
    ],
  },
  {
    id: "truffle_oil",
    name: "Truffle Oil",
    tier: "special",
    base_price: 1050,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [
      { id: "truffle", qty: 1 },
      { id: "cooking_oil", qty: 1 },
    ],
  },
  {
    id: "shirt",
    name: "Shirt",
    tier: 2,
    base_price: 350,
    peg: PEG_COTTON,
    category: "crafted",
    recipe: [{ id: "fabric", qty: 2 }],
  },
  {
    id: "blue_sweater",
    name: "Blue Sweater",
    tier: 3,
    base_price: 520,
    peg: PEG_COTTON,
    category: "crafted",
    recipe: [
      { id: "yarn", qty: 2 },
      { id: "blue_dye", qty: 1 },
    ],
  },
  {
    id: "dyed_fabric",
    name: "Dyed Fabric",
    tier: 3,
    base_price: 560,
    peg: PEG_COTTON,
    category: "crafted",
    recipe: [
      { id: "fabric", qty: 1 },
      { id: "red_dye", qty: 1 },
    ],
  },
  {
    id: "pearl_necklace",
    name: "Pearl Necklace",
    tier: "special",
    base_price: 1400,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [
      { id: "pearl", qty: 2 },
      { id: "thread", qty: 1 },
    ],
  },
  {
    id: "lobster_bisque",
    name: "Lobster Bisque",
    tier: 3,
    base_price: 600,
    peg: PEG_CORN,
    category: "crafted",
    recipe: [
      { id: "lobster", qty: 1 },
      { id: "milk", qty: 2 },
    ],
  },
];
